CREATE TABLE Generos(
	id NUMBER(7) PRIMARY KEY,
	nombre VARCHAR2(10) NOT NULL
);

ALTER TABLE Generos ADD (
  CONSTRAINT Generos_pk PRIMARY KEY (ID));

CREATE SEQUENCE Generos_seq START WITH 1;

CREATE OR REPLACE TRIGGER Generos_pk 
BEFORE INSERT ON Generos 
FOR EACH ROW

BEGIN
  SELECT Generos_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/