CREATE TABLE Zonas(
	id NUMBER(7) PRIMARY KEY,
	nombre VARCHAR2(20)
);

ALTER TABLE Zonas ADD (
  CONSTRAINT Zonas_pk PRIMARY KEY (ID));

CREATE SEQUENCE Zonas_seq START WITH 1;

CREATE OR REPLACE TRIGGER Zonas_pk 
BEFORE INSERT ON Zonas 
FOR EACH ROW

BEGIN
  SELECT Zonas_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/