CREATE TABLE TiposPredio(
	id NUMBER(7) PRIMARY KEY,
	nombre VARCHAR2(20)
);

ALTER TABLE TiposPredio ADD (
  CONSTRAINT TiposPredio_pk PRIMARY KEY (ID));

CREATE SEQUENCE TiposPredio_seq START WITH 1;

CREATE OR REPLACE TRIGGER TiposPredio_pk 
BEFORE INSERT ON TiposPredio 
FOR EACH ROW

BEGIN
  SELECT TiposPredio_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/