CREATE TABLE Distritos(
	id NUMBER(7) PRIMARY KEY,
	nombre VARCHAR2(20)
);

ALTER TABLE Distritos ADD (
  CONSTRAINT Distritos_pk PRIMARY KEY (ID));

CREATE SEQUENCE Distritos_seq START WITH 1;

CREATE OR REPLACE TRIGGER Distritos_pk 
BEFORE INSERT ON Distritos 
FOR EACH ROW

BEGIN
  SELECT Distritos_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/