CREATE TABLE Bancos(
	id NUMBER(7) PRIMARY KEY,
	nombre VARCHAR2(15)
);

ALTER TABLE Bancos ADD (
  CONSTRAINT Bancos_pk PRIMARY KEY (ID));

CREATE SEQUENCE Bancos_seq START WITH 1;

CREATE OR REPLACE TRIGGER Bancos_pk 
BEFORE INSERT ON Bancos 
FOR EACH ROW

BEGIN
  SELECT Bancos_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/