CREATE TABLE Plan(
  id NUMBER(7) PRIMARY KEY,
  CantMegas NUMBER(15) NOT NULL,
  PrecioMensual FLOAT NOT NULL,
  TipoPlan_id NUMBER(2) NOT NULL,
  FOREIGN KEY (TipoPlan_id) REFERENCES TiposPlan

);

ALTER TABLE Plan ADD (
  CONSTRAINT Plan_pk PRIMARY KEY (id));

CREATE SEQUENCE Plan_seq START WITH 1;

CREATE OR REPLACE TRIGGER Plan_pk 
BEFORE INSERT ON Plan 
FOR EACH ROW

BEGIN
  SELECT Plan_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/